### ISSUE TITLE
How did you come to the idea to write your own static site generator?

### ISSUE THREAD

**Issue by svetlyak40wt** [pyramidi0n/crystal#1]
Did you know there is alread [Coleslaw](https://github.com/coleslaw-org/coleslaw) exists?

I did. And I used Coleslaw a few years until this spring, when I decided to write my own static site generator: [StatiCL](https://40ants.com/staticl/). I wanted a more generic solution than Coleslaw does.

What is your story behind Crystal?

**Comment by pyramidi0n** [comment]
Hey!

Yep, I knew about Coleslaw. Didn't know about StatiCL, however - thanks for the link.

I'd been using an ad hoc collection of Lisp glue code to publish some static websites for a few years. Crystal is just an attempt to consolidate that stuff in one place.

It's extremely basic. It will probably remain extremely basic.

**Comment by dertuxmalwieder** [comment]
If something’s missing in Coleslaw, I’m glad to merge your pull requests.
